laptop.register_theme("Undersea", {
	desktop_background = "laptop_theme_undersea_desktop_background.png",
	app_background = "laptop_theme_undersea_app_background.png",
	major_button = "laptop_theme_undersea_major_button.png",
	major_textcolor = "#FFFFFF",
	minor_button = "laptop_theme_undersea_minor_button.png",
	minor_textcolor = "#FFFFFF",
	back_button = "laptop_theme_undersea_back_button.png",	
	back_textcolor = "#FFFFFF",
	exit_button = "laptop_theme_undersea_exit_button.png",
	exit_textcolor = "#FFFFFF",
	contrast_background = "laptop_theme_undersea_minor_button.png",
	desktop_icon_button = "laptop_theme_undersea_minor_button.png",
	table_bgcolor="#FFFFFF",
	table_highlight_bgcolor='#888888',
	muted_textcolor = "#444444",
	table_border = 'true',
	os_min_version = '7.00',
	exit_character = " ",
	back_character = " ",
})
